### ISSUE TITLE
Add ability to prioritize daemon

### ISSUE THREAD

**Issue by marcincichocki** [marcincichocki/breach-protocol-autosolver#210]
It would be nice to be able to focus on one specific daemon instead of using default higher index is better strategy when selecting sequence.

In practice it would mean that every sequence with given daemon would receive big boost in strength so they are sorted accordingly. One thing to note is that it doesn't mean daemon will be solved(although it's very likely), just that it will be prioritized.

Stuff required in client would include new keybind options for daemons(5x). ~~By default those things would **not** be bound.~~

TODO:

- [x] add stuff to core to allow sorting sequences by daemon index. Done via #211 
- [x] create keyboard manager to keep track of new keybinds. Done via #212 
- [x] update keybind component to be less tightly coupled `keybind` option. Done via #213 
- [x] merge all above together
